version: '3'

services:
  relay:
    build: .
    environment:
      - REDIS_URL=redis://redis
      - RELAY_BASE_URL=http://192.168.1.108:8080
      - VIEWER_BASE_URL=http://localhost:3000
      - PORT=8080
    ports:
      - '8080:8080'
    volumes:
      - '.:/root/relay/'
    networks:
      - backend
    depends_on:
      - redis

  redis:
    image: 'redis:3.2'
    networks:
      - backend

  redis-commander:
    image: 'ficusio/redis-commander'
    command: '--redis-host redis'
    depends_on:
      - redis
    ports:
      - '8081:8081'
    networks:
      - backend

networks:
  backend:
