version: '3'

services:
  relay:
    build: .
    environment:
      - VIRTUAL_HOST=relay.icctv.gq
      - RELAY_BASE_URL=http://relay.icctv.gq
      - VIEWER_BASE_URL=http://icctv.gq
      - PORT=8080
    expose:
      - '8080'
    networks:
      - backend
    depends_on:
      - redis
    deploy:
      restart_policy:
        condition: on-failure

  nginx:
    image: 'jwilder/nginx-proxy'
    environment:
      - ENABLE_IPV6=true
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  redis:
    image: 'redis:3.2'
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure

networks:
  backend:
