version: '3'

services:
  relay:
    build: .
    environment:
      - REDIS_URL=redis://redis
      - RELAY_BASE_URL=http://192.168.1.108:8080
      - VIEWER_BASE_URL=http://localhost:3000
      - PORT=8080
    ports:
      - '8080:8080'
    networks:
      - backend
    depends_on:
      - redis

  redis:
    image: 'redis:3.2'
    networks:
      - backend

networks:
  backend:
